services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: smarthunt_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  api:
    build: .
    command: sh -c "uvicorn presentation.api.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgrespassword@db:5432/smarthunt_db
      - REDIS_URL=redis://redis:6379/0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  celery_worker:
    build: .
    # Ограничиваем concurrency до 1 из-за 1 vCPU и малого объема RAM
    command: celery -A infrastructure.task_queue.celery_app worker -l info --concurrency=1 --max-tasks-per-child=50
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgrespassword@db:5432/smarthunt_db
      - REDIS_URL=redis://redis:6379/0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  db-data:
